### ISSUE TITLE
Publish an esm version of `ampproject/animations`

### ISSUE THREAD

**Issue by rsimha** [ampproject/animations#10]
From https://github.com/ampproject/amphtml/pull/19175#issuecomment-438802754

> @sparhami @cathyxz I'm in the process of upgrading closure compiler, and am running into some problems due to this PR. Specifically, the @ampproject/animations module appears to be common JS, and we will no longer support implicit transformation to ESM via closure. Any chance there's an ESM version of this library that we can use?

**Comment by sparhami** [comment]
Added a comment here: https://github.com/ampproject/amphtml/pull/19175#issuecomment-438810725, an esm output is already available. I think it might work with a newer version of Closure Compiler.

**Comment by rsimha** [comment]
Yes, I was able to use the esm output you pointed me to. Thanks!
